### ISSUE TITLE
Feature request: show column as usual when it would otherwise not show

### ISSUE THREAD

**Issue by pjcj** [Bekaboo/deadcolumn.nvim#10]
Thanks for writing and releasing deadcolumn.  I have a feature request if it fits in with your plans.

I like the concept of deadcolumn but I want to see the columns permanently.  Do you think there could be an option such that when the columns aren't currently shown they could be shown is the default fashion?

**Comment by Bekaboo** [comment]
I don't get your point. If you want to see the colored column all the time, simply set `cc` to some value and don't use this plugin. Is that what you expected? If not please elaborate.

**Comment by pjcj** [comment]
Without the plugin I have `ColorColumn` set to a pale colour and can always see it.  With the plugin I get the nice behaviour of the column getting darker as the line length approaches the limit and flipping as the limit is hit.  What I'd really like is both.  I always want the pale column highlight, but as the line length approaches the limit I want the colour to get darker and then flip at the limit.  Does that make sense?

**Comment by Bekaboo** [comment]
Sorry I have no interest in implementing this feature. PR is welcome.

**Comment by Bekaboo** [comment]
Sorry I have no interest in implementing this feature. PR is welcome.

**Comment by pjcj** [comment]
No problem, thanks for looking.
