### ISSUE TITLE
Feature request: allow text on the column

### ISSUE THREAD

**Issue by pjcj** [Bekaboo/deadcolumn.nvim#11]
It looks like the way you use columns is that the text must finish before the column.  I like to allow text on the column but not beyond it.  Do you think there could be an option to allow text on the column?

**Comment by Bekaboo** [comment]
This is possible by allowing users to pass a callback function to decide when the color should change, I will work on this when I have time.

**Comment by Hubro** [comment]
@pjcj Is it not an alternative to just set `colorcolumn` to `n-1`?

**Comment by Bekaboo** [comment]
Implemented in commit 1c35515.
