### ISSUE TITLE
Plugin doesn't work out of the box

### ISSUE THREAD

**Issue by simonmandlik** [Bekaboo/deadcolumn.nvim#13]
Hi, thanks for working on this cool plugin. I decided to give it a try, because it seemed to have the most features, but can't make it work, even in vanilla vim.

repro.lua:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    -- "Bekaboo/deadcolumn.nvim"
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd[[hi ColorColumn guibg=red]]
vim.cmd[[set textwidth=20]]
vim.cmd[[set colorcolumn=-10,25,+2]]
```

When I run `nvim -u repro.lua test.txt`, it works as expected

<img width="887" alt="image" src="https://github.com/Bekaboo/deadcolumn.nvim/assets/16707112/f575e496-3551-4a97-b99d-7dc30c4ef1e0">

but when I uncomment the line with the plugin, install it and start typing, nothing happens

<img width="887" alt="image" src="https://github.com/Bekaboo/deadcolumn.nvim/assets/16707112/3c09648b-6d73-413d-b913-75c9acb525cd">

**Comment by Bekaboo** [comment]
@simonmandlik @Normanras I'am planning rewrite this plugin utilizing the `winhl` feature instead of changing the user option `&cc` (which is the current implementation) and that should make it much more stable. Right now this pligin is filled with hacky and unnessarily complecated code because `winhl` feature has bugs (see neovim/neovim#23016 and neovim/neovim#23227) back when this plugin was written.

**Comment by Normanras** [comment]
Awesome! I won't submit any issues then. I realized there was some weird stuff happening as it interacted with other plugins (notably, Folke's Styler), so good to know something more stable is coming. Let me know if you need any help!

**Comment by Bekaboo** [comment]
This plugin has been refactored to use `winhl` instead of messing around with `cc` and should be much stabler now, see commit ce15b1750c3bb1f7d2bc26492491f8cdcd313ff5, commit 0b271926037153e7aa69bfab366ff8749ebba521

**Comment by simonmandlik** [comment]
I've just tried the MWE from this issue and I am still getting no color column :(

**Comment by Bekaboo** [comment]
@simonmandlik Hi, can you confirm the problem persists using the minimal config and `nvim --clean -u minimal.lua`?

**Comment by simonmandlik** [comment]
Yes, I'm on `v0.10.0-dev-1506+g610f50dda-Homebrew`

https://github.com/Bekaboo/deadcolumn.nvim/assets/16707112/5ea29ce1-c228-466e-b81a-3774b4e612c0

**Comment by Bekaboo** [comment]
That's strange, I will see if I can reproduce it using the same version of neovim as yours. Currently I cannot reproduce using `dev-2075`, the plugin should work on both versions though.

**Comment by Bekaboo** [comment]
@simonmandlik You don't set `&termgicolors`. Try setting it using `:set termguicolors`.
