### ISSUE TITLE
Setting winhighlight conflicts with other plugins

### ISSUE THREAD

**Issue by backdround** [Bekaboo/deadcolumn.nvim#18]
In a nutshell `winhighlight` conflicts with `vim.api.nvim_win_set_hl_ns`. The documentation says that either way of setting highlights takes precedence over another way. In practice, it means that if a highlight is set by `winhighlight`, it completely disables all highlights that were set by `nvim_win_set_hl_ns`.

<details>
<summary>winhighlight help</summary>

```vimhelp
					*'winhighlight'* *'winhl'*
'winhighlight' 'winhl'	string	(default "")
			local to window
	Window-local highlights.  Comma-delimited list of highlight
	|group-name| pairs "{hl-from}:{hl-to},..." where each {hl-from} is
	a |highlight-groups| item to be overridden by {hl-to} group in
	the window.

	Note: highlight namespaces take precedence over 'winhighlight'.
	See |nvim_win_set_hl_ns()| and |nvim_set_hl()|.
```

</details>

<details>
<summary>nvim_win_set_hl_ns help</summary>

```vimhelp
nvim_win_set_hl_ns({window}, {ns_id})                   *nvim_win_set_hl_ns()*
    Set highlight namespace for a window. This will use highlights defined
    with |nvim_set_hl()| for this namespace, but fall back to global
    highlights (ns=0) when missing.

    This takes precedence over the 'winhighlight' option.

    Parameters: ~
      • {ns_id}  the namespace to use

```

</details>

Snippet to test:
```lua
local ns = vim.api.nvim_create_namespace("UserTestHighlight")
vim.api.nvim_set_hl(ns, "Function", { fg = "#00FF66" })

vim.keymap.set("n", "<C-w>", function()
  vim.api.nvim_win_set_hl_ns(0, ns)
end)

vim.api.nvim_create_autocmd({ 'CursorMoved', 'TextChanged', }, {
  callback = function()
    vim.wo[0].winhl = "String:"
  end
})
```

https://github.com/Bekaboo/deadcolumn.nvim/assets/17349169/23eac6d9-ba86-4249-aa36-6215b1e953ca

[ccc.nvim](https://github.com/uga-rosa/ccc.nvim/issues/99) is one of the plugin that is in conflict with the current plugin.

I think that sticking to the lua api is a good way to solve the problem

**Comment by Bekaboo** [comment]
Thanks for reporting this issue. I doubt if there's anything we can do for this issue given how `winhl` and highlight namespace work in nvim. Switching to `nvim_win_set_hl_ns` requires heavy refactor and I have no intention to do this because. I don't use ccc.nvim

**Comment by backdround** [comment]
I'll see if i can do something about it.

Thank you for the nice plugin!

**Comment by backdround** [comment]
I checked the API. This isn't possible to have several namespaces set simultaneously for a window by `nvim_win_set_hl_ns`. So switching to `nvim_win_set_hl_ns` won't fix the problem.

I see only two way of fixing this:
- Set highlight globally and manage `colorcolumn` manually (to show / hide it)
- Use virtual text

**Comment by Bekaboo** [comment]
> Set highlight globally and manage colorcolumn manually (to show / hide it)

Before commit b7cdc07c97abf54656c49763da935ca147318101 deadcolimn manage colorcolumn manually, but this method is proven unreliable and can easily cause confusion and bugs. Nvim/Vim uses a very complex mechanism to set options, especially for global-local options like colorcolumn (see `:h global-local`) and that's why I refactored this plugin to use winhl instead of managing colorcolumn manually.



> Use virtual text

Needs complete rewrite.

**Comment by Bekaboo** [comment]
The only way I see to fix this is requiring ccc.nvim to switch to winhl. One can append/remove hlgroup mapping to winhl without affecting existing hl mappings, see `:h vim.opt:append()`, `:h vim.opt:remove()`.
