### ISSUE TITLE
Cursor Losing Column Position Issue in Nightly Version

### ISSUE THREAD

**Issue by bassamsdata** [Bekaboo/deadcolumn.nvim#19]
Firstly, I want to express my sincere thanks for this plugin.

**Description:**
I've encountered an issue where the cursor loses its column position when scrolling down with the plugin active. This problem persists in nightly builds (I've tried multiple recent versions), but it doesn't occur in stable builds.

While I understand nightly builds may have issues, I wanted to report this problem for consideration.

**To Reproduce:**
1. Open a Lua file filled with long lines (exceeding 80 columns).
2. Start editing the file.
3. Scroll down using the 'j' key down a long line, and the cursor will lose its position and jump to column 0.

<details>
<summary> Code to Reproduce </summary>

```sh
mkdir ~/.config/testcolumn
cd ~/.config/testcolumn
touch init.lua
NVIM_APPNAME=testcolumn nvim
```
init.lua file
```lua
vim.opt.number = true
vim.opt.relativenumber = true

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	"Bekaboo/deadcolumn.nvim",
	event = { "InsertEnter" },
	config = function()
		vim.opt.colorcolumn = "80"
		local opts = {
			modes = { "n", "i" },
			blending = {
				threshold = 0.75,
			},
			warning = {
				alpha = 0.1,
			},
		}
		require("deadcolumn").setup(opts)
	end,
})
```
</details>

The video demonstrates that the issue does not exist before activating the plugin. However, after inserting and saving the file, the problem occurs when scrolling down a long line.
Video:

https://github.com/Bekaboo/deadcolumn.nvim/assets/105807570/44e07f6e-fef1-45cb-82e4-7cc8bb30047f

OS: MacOS
term: wezterm
neovim version: 
```sh
NVIM v0.10.0-dev-2355+g1c7b0b9d5
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
```

Thank you

**Comment by bassamsdata** [comment]
Thank you for the prompt answer
So `vim.opt.colorcolumn` could be the reason here. I'll do some tests again and check if I can reproduce it in different situations without the plugin.

**Comment by Bekaboo** [comment]
@bassamsdata deadcolumn has been refactored to use winhl option instead of colorcolumn option now.

**Comment by Bekaboo** [comment]
This bug has been reported to neovim: https://github.com/neovim/neovim/issues/27470

**Comment by bassamsdata** [comment]
thank you, I was tinkering with the time thing related to the autocmd of CursorMoved and tried to defer it but yea, the  issue persisted. 
the minimal.lua file reproduce the issue indeed, thanks again.

**Comment by Bekaboo** [comment]
Should be fixed by https://github.com/neovim/neovim/pull/27515/files
