### ISSUE TITLE
Interop with plugins that change column character

### ISSUE THREAD

**Issue by jeanlucthumm** [Bekaboo/deadcolumn.nvim#25]
Was previously using this: https://github.com/xiyaowong/virtcolumn.nvim?tab=readme-ov-file

Just tested it and it seems to override the functionality of this plugin. Would be nice if we can combine the two or get such an option as part of this. (single pixel column looks really nice)

**Comment by Bekaboo** [comment]
Thanks for your idea. However, the plugin you mentioned uses extmarks to mimic the behavior of native colorcolumn while this plugin uses native colorcolumn provided by neovim C core, so that's impossible to make them work together.
