### ISSUE TITLE
Different colors for each colorcolumn

### ISSUE THREAD

**Issue by rbhanot4739** [Bekaboo/deadcolumn.nvim#26]
Hi,

I am not sure if the plugin supports this but having the ability to have different colors for each color column would be useful in some contexts rather than having same color for each colorcolumn.

For example, if the `colorcolumn` for a python file is set to `80,90,120` then mapping it to color code table like `{'Grey', 'Yellow', 'Red'}` (color names are just for semantic purposes only), makes easier for the user to get visual feedback when they are going from Normal > Warning > Error line lengths.

**Comment by Bekaboo** [comment]
That's a great idea however it's not possible without a full rewrite. The plugin uses native colorcolumn provided by nvim C core instead of extmarks, which does not support different colors for each colorcolumn :(
