### ISSUE TITLE
This plugin doesn't work sometimes

### ISSUE THREAD

**Issue by mitchellwrosen** [Bekaboo/deadcolumn.nvim#9]
Sorry for the low-quality bug report, but sometimes this plugin just... doesn't work. I enter insert mode and see no color column, despite there being a long line visible on my screen (I'm using scope `'visible'`). Restarting vim fixes the issue.

I peeked at the implementation, and I see it's incredibly involved and complicated. So thanks for packaging this up into a plugin and trying to maintain all of the complexity behind an interface, but unfortunately, it seems something so far was missed.

Has anyone else experienced this issue? I'm afraid I don't have a reliable repro.

**Comment by Bekaboo** [comment]
Hi, thanks for reporting! I'm glad to fix it as long as there is a minimal config that can reproduce this issue. You can start from the default minimal config provided in the issue template.

**Comment by gilbh** [comment]
Something I noticed is that I can't get the plug to work if I place `set colorcolumn=120` in the autocmd (for .py in this case). Only if I execute the set command "manually" or if I put it in the general space of the `.vimrc` will it work on start up ... perhpas b/c of late binding via Lazy?

**Comment by Bekaboo** [comment]
This plugin has been reworked to use `winhl` instead of messing around with `cc` and should be much stabler and should not have unexpected behavior now, see commit ce15b1750c3bb1f7d2bc26492491f8cdcd313ff5, commit 0b271926037153e7aa69bfab366ff8749ebba521
